- docs/User-Guide_Getting-Started.md
can be useful as to give a link to forum users
> added section 'Prerequisites for NEW users'

- docs/User-Guide_Advanced-Features.md
See: https://forum.armbian.com/index.php?/topic/490-docker-on-armbian/&page=3#comment-30204
The docs should show the official way to install Docker, if this works for a reasonable amount of users. NB! I have **not** tested it myself on armbian!
> Install Docker the official way

- docs/board_details/odroidhc1.md
- docs/known_issues/odroidhc1.md
per a implied suggestion in a forum (I could not find a formal bug / RFE), I created HC1 entries as indicated
> add initial HC1 documentation

- docs/User-Guide_Armbian-Config.md
To be honest, it wasn't 110% clear that armbian-config was the name to enter...
> armbian-config is the name of the tool

- docs/Developer-Guide_Building-with-Docker.md
Hello again @igorpecovnik @zador-blood-stained 
Updated RHEL/CentOS/Fedora instructions, making use of the Docker config build recipe.
Enjoy your weekend! o/
> Docker docs: Updated RHEL examples

- docs/User-Guide_Getting-Started.md
The changes reflect what has not received any negative comment [in this thread](https://forum.armbian.com/topic/6281-bordsupport-general-discussion-project-aims/?do=findComment&comment=50582). So I send you the PR.
> added stable and minor changes

- docs/User-Guide_Getting-Started.md
Reverts armbian/documentation#14
Merged too soon. Sorry.
> Revert "added stable and minor changes"

- docs/Developer-Guide_Build-Options.md
This time, a hopefully less controversial PR to improve the documentation. :)
Should only be merged, when you merge this one too:
https://github.com/armbian/build/pull/956
> Add LIB_TAG description

- docs/User-Guide_Armbian-Config.md
ownyourbits/nextcloudplus does no longer exist
> Update link to NextCloudPi URL

- docs/User-Guide_Armbian-Config.md
as this was removed in 5.76 https://github.com/armbian/documentation/commit/f309c20f4bf8ef82e031664f1d21508f54d
> Remove exagear desktop from userguide

- docs/Developer-Guide_Build-Options.md
took text from https://github.com/armbian/build/blob/376c1b05515ab1e459edc2c6d42b38f3c65699d2/config/templates/config-example.conf#L10
> Add oldcache option to CLEAN_LEVEL

- docs/Developer-Guide_Building-with-Docker.md
Addresses:
- https://github.com/armbian/documentation/issues/53
- https://github.com/armbian/build/issues/1618
> Clarify building of image using Docker

- docs/User-Guide_Advanced-Features.md
> Small typo / grammar

- docs/Developer-Guide_Build-Options.md
- docs/Developer-Guide_Build-Preparation.md
- docs/Hardware_Allwinner-H3.md
- docs/Hardware_Allwinner-H5-A64.md
- docs/Hardware_Allwinner-H6.md
- docs/Hardware_Allwinner.md
- docs/User-Guide_Armbian-Config.md
- docs/User-Guide_Basic-Troubleshooting.md
- docs/User-Guide_Fine-Tuning.md
- docs/User-Guide_Getting-Started.md
- mkdocs.yml
**Attention:** I added some comments to various commits because stuff were unclear and needs to be reviewed!
> Add basic Allwinner H6 hardware-specific doc

- docs/Quick_facts.md
- docs/User-Guide_Advanced-Features.md
- docs/User-Guide_Getting-Started.md
- docs/index.md
Please take attention to look at the commit comments.
> Mostly cosmetics

- docs/Developer-Guide_User-Configurations.md
https://forum.armbian.com/topic/11491-real-time-operating-system/?tab=comments#comment-99641
> Add example for kernel branch user adjustment

- docs/User-Guide_Fine-Tuning.md
Taken from https://forum.armbian.com/topic/10403-add-undetected-hdmi-resolution-to-x11xorg/ (thx)
> Add resolution adjustment within xorg with xrandr

- docs/Developer-Guide_Build-Preparation.md
- docs/Developer-Guide_Build-Process.md
And some additional various cosmetics
> Push to Focal

- docs/Developer-Guide_Build-Preparation.md
https://forum.armbian.com/topic/13914-ubuntu-2004-miniiso-url-documentation-update-needed/
> Update Mini ISO URL

- docs/Release_Changelog.md
Date is a bit off since some torrents needed fixing as well.
> Update to 20.05.2

- docs/irc.md
I leave it up to you to find a place within the structure for this.
Also you should test each command before merging.
Closes AR-302
> Add IRC documentation

- docs/Community_IRC.md
> Maybe fixes Services section

- docs/Developer-Guide_Build-Options.md
Replace the two variables of IGNORE_UPDATES FORCE_CHECKOUT
with OFFLINE_WORK
> Delete IGNORE_UPDATES FORCE_CHECKOUT, new OFFLINE_WORK

- docs/Community_IRC.md
> Probably fixes connect section

- docs/Process_Managing_Workflow.md
- docs/Process_Release-Model.md
- mkdocs.yml
* Jira backlog documetation
* update release process to reflect -rc branch is rolling
> Backlog management

- docs/User-Guide_Basic-Troubleshooting.md
Add a section about testing SD cards with f3
After reading about all the fake SD cards about, I thought it would be wise to add a section about it to the troubleshooting section of the user guide.
https://fight-flash-fraud.readthedocs.io/en/latest/usage.html
> Add a section about testing SD cards with f3

- docs/Developer-Guide_User-Configurations.md
TODO someone who has more experience should probably adjust the wording and maybe explain how this actually happens in the compile.sh script. 
Here is an IRC log of the conversation which prompted this PR: https://picopublish.sequentialread.com/files/irc_log.txt
> State that userpatches stuff will be automatically virtualized for build target

- docs/Developer-Guide_User-Configurations.md
TODO someone who has more experience should probably adjust the wording and maybe explain how this actually happens in the compile.sh script. 
Here is an IRC log of the conversation which prompted this PR: https://picopublish.sequentialread.com/files/irc_log.txt
> clean up ambigous/confusing wording

- docs/User-Guide_Advanced-Features.md
I had to unbrick during the weekend (fun fun fun), so here is a little update to the documentation.
> Rework of unbrick section

- docs/User-Guide_Advanced-Features.md
Just made a fresh install of Docker on my Armbian 20.08.17 Buster with Linux 5.8.17-rockchip64.
> Up to date Docker install for Armbian Buster

- docs/Community_Governance.md
@piter75 is this correct this way?
> Add piter as maintainer

- README.md
- docs/Community_Governance.md
- docs/Developer-Guide_Build-Preparation.md
- docs/Developer-Guide_Building-with-Docker.md
- docs/Developer-Guide_FEL-boot.md
- docs/Developer-Guide_User-Configurations.md
- docs/Developer-Guide_Using-Vagrant.md
- docs/Hardware_Allwinner-A20.md
- docs/Hardware_Allwinner-H3.md
- docs/Hardware_Allwinner-H5-A64.md
- docs/Hardware_Allwinner-H6.md
- docs/Hardware_Allwinner.md
- docs/Hardware_Freescale-imx6.md
- docs/Hardware_Marvell.md
- docs/Process_Contribute.md
- docs/Process_Managing_Workflow.md
- docs/Process_Merge-Policy.md
- docs/Process_Release-Model.md
- docs/Quick_facts.md
- docs/Release_Changelog.md
- docs/User-Guide_Advanced-Features.md
- docs/User-Guide_Allwinner_overlays.md
- docs/User-Guide_Armbian-Config.md
- docs/User-Guide_Basic-Troubleshooting.md
- docs/User-Guide_Fine-Tuning.md
- docs/User-Guide_Getting-Started.md
- docs/index.md
Also a few other minor formatting changes, and moved a couple things, while I was at it.  Importantly however, I did not change the name of any headings, so as not to break any existing links.
> Fix headline depth/semantics throughout docs

- docs/Release_Changelog.md
> Changelog cleanup

- docs/board_details/pine64.md
Running the mainline kernel and didn't figure this out until a forum post. Updating docs so others don't have to go through the effort again.
> Update Pine64 doc for LCD enable

- docs/Developer-Guide_Build-Preparation.md
- docs/Developer-Guide_FEL-boot.md
- docs/Developer-Guide_User-Configurations.md
- docs/Process_Merge-Policy.md
- docs/Process_Release-Model.md
- docs/User-Guide_Armbian-Config.md
- docs/User-Guide_Getting-Started.md
- docs/known_issues/sun4i.md
- docs/known_issues/sun50iw1.md
- docs/known_issues/sun7i.md
- docs/known_issues/sun8i.md
Also remove some outdated sunxi info
> Rename dev to edge

- docs/Community_IRC.md
- docs/index.md
> fix freenode

- docs/Developer-Guide_Build-Options.md
> add hirsute

- docs/User-Guide_Board-Support-Rules.md
- docs/index.md
- mkdocs.yml
Bring in definitions for support.   Remove information we can't maintain. (list of SoCs)
> add new support definitions

- docs/User-Guide_Getting-Started.md
Per this thread: https://forum.armbian.com/topic/19360-no-properly-formatted-sha-checksum-lines-found/?do=findComment&comment=131626
> Correct documentation on how to use shasum

- docs/Developer-Guide_Build-Options.md
https://github.com/armbian/build/pull/3342
> Add support for rootfs / toolchain bind (u)mount

- docs/Release_Board-Maintainers.md
> Board Maintainers polish

- docs/Release_Board-Maintainers.md
Somehow I managed to miss him before.
> docs/Release_Board-Maintainers.md: Add piter75 to xref table

- docs/Release_Board-Maintainers.md
My editor also re-aligned both tables, causing a large diff, but that
was the only real change.
> docs/Release_Board-Maintainers.md: Add Technicavolous to xref table

- docs/Developer-Guide_Building-with-Docker.md
Much of the wording was rather confusing
> Clean up grammar of new docker-shell docs

- mkdocs.yml
enable search plugin...
tested locally via `Mkdocs serve`
> add search plugin

- docs/Developer-Guide_Build-Preparation.md
related https://github.com/armbian/build/pull/3600
> Bump build environment to Jammy

- docs/User-Guide_FAQ.md
simple language to provide a response about "sending a board"
> update faq about "sending a board"

- docs/Release_Board-Maintainers.md
Added myself as official maintainer for orangepizero2; also added myself in github -> forum name translation table.
> Add qiurui as maintainer for orangepizero2

- docs/Release_Changelog.md
> Notes on bug-fix release

- docs/Release_Changelog.md
Added information about new desktop flavors that were made available in 22.05.4
> Updated for 22.05.4 release

- docs/Developer-Guide_Using-Vagrant.md
Update documentation following https://github.com/armbian/build/pull/3971
> Update vagrant documentation

- docs/User-Guide_Advanced-Features.md
`User-Guide_Advanced-Features.md`:
* fix typo (than → then),
* remove extra spaces,
* add code blocks.
> User-Guide_Advanced-Features.md: typo, minor fixes

- docs/Release_Board-Maintainers.md
I left more notes in the individual commits.
> Tidying up Board Maintaners page

- docs/User-Guide_Armbian-Config.md
Add notice about rewrite and level of attention the current tool receives.
> Add hint about rewrite

- docs/Release_Board-Maintainers.md
https://github.com/armbian/build/pull/4063
> Deprecating old pinebook and cubox-i

- docs/User-Guide_FAQ.md
Fixing the link. Thanks @morrownr
> Change link to entry page

- docs/Hardware_Allwinner-H3.md
- docs/Release_Changelog.md
- docs/User-Guide_Getting-Started.md
- docs/index.md
- docs/known_issues/odroidxu4.md
Merge after we are done with testings and when its pushed out to users. Next major release ...
> Replace nand-sata-install with armbian-install

- docs/Community_IRC.md
> Remove Twitter integration

- docs/Developer-Guide_Build-Options.md
Relates to https://github.com/armbian/build/issues/4421 and to pull request https://github.com/armbian/build/pull/4422
> Add UBOOT_ONLY option doc

- docs/Process_Release-Model.md
Also present in https://forum.armbian.com/events/
> Add date to next year

- docs/Developer-Guide_Build-Options.md
- Updated KERNEL_ONLY doc to warn for deprecation
- Relates to pull request https://github.com/armbian/build/pull/4455
> Add doc for option BUILD_ONLY

- docs/Release_Changelog.md
This release represent altruistic contribution, often hard and sometimes boring work. Thank you @hzyitc, @150balbes, @rpardini, @paolosabatino, @The-going, @Manouchehri, @belegdol, @amazingfate, @EvilOlaf, @mhoffrog, @marcone, @joekhoobyar, @adeepn, @brentr, @SteeManMI, @TheLinuxBug, @Tonymac32, @aiamadeus, @ashthespy, @mklein-de, @schwar3kat, @Heisath, @iamdrq, @iav and all people which are busy developing in the silence, busy with life, all those that are with us and they didn't left any formal traces in our [Jira](https://armbian.atlassian.net/). Staff that is developing and maintaining support infrastructure, our partners, our families, our pets 🐱 ...
Thank you for your contribution to open source and to the #armbian project. We again did a tremendous improvements on all levels, solve …
> Preparing for 22.11 release

- docs/Developer-Guide_Build-Preparation.md
This PR fix the download link of the ubuntu server image.
Signed-off-by: Stefan Dej <meteyou@gmail.com>
> docs: fix ubuntu download link

- docs/User-Guide_FAQ.md
Bump old-old-stable to old-stable
Fix link to forums
> Small cosmetics

- docs/index.md
Move from "supported" more into "maintained" direction
add hint about ignoring bug reports
> Adjust wording

- docs/Developer-Guide_Build-Preparation.md
Based on https://github.com/armbian/build/issues/4690
> adjust git command

- docs/Developer-Guide_Build-Options.md
See ./lib/functions/configuration/interactive.sh 'interactive_config_ask_kernel_configure'
> dev-guide: document prebuilt for KERNEL_CONFIGURE

- docs/Developer-Guide_Build-Options.md
See ./lib/functions/configuration/interactive.sh 'interactive_config_ask_build_only'
> dev-guide: Document missing 'default' option

- docs/Community_IRC.md
Replace redirect Discord URL with official custom one
Hide ArmbianTwitter. 
Adjust relay bot name and description
> update IRC docs

- docs/User-Guide_Getting-Started.md
[AR-1748]
[AR-1748]: https://armbian.atlassian.net/browse/AR-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add instructions for userspace dist-upgrades

- docs/Developer-Guide_Extensions-Hooks.md
> Fix - looks like a typo

- docs/User-Guide_Getting-Started.md
Adjust userspace names to reflect the upcoming userspace releases
Do some rephrasing about what branches and images are
> Bump to future, rephrasing

- docs/Developer-Guide_Build-Options.md
> CREATE_PATCHES deprecated

- docs/User-Guide_Getting-Started.md
consider NAND installations outdated while leaving the option for tinkering.
> deprecation notice NAND

- docs/Community_IRC.md
mention announcements channel into both Libera and OFTC
> Add #armbian-announcements to relay

- docs/Developer-Guide_Build-Preparation.md
Nico revisited his four year old video about building Armbian in the mean time to cover the changes of the ng build framework
> update embedded video

- docs/User-Guide_FAQ.md
> adjust userspace upgrade instructions

- docs/User-Guide_FAQ.md
Add hint for missing `armbian-config` on minimal images
> add armbian-config

- docs/User-Guide_Armbian-Config.md
* old domain was taken by advertisment company so better use new domain
* change to full project name instead of short name
> Update nextcloudpi in User-Guide_Armbian-Config.md

- docs/Process_Release-Model.md
add recent meeting
variable starting time for upcoming meetings
> Add latest meeting

- .github/workflows/release.yaml
- mkdocs.yml
Guess I disabled PDF generation inadvertently
> re-enable pdf build; 2023 -> 2024

- docs/Release_Changelog.md
> Wrong year and month

- docs/Hardware_Rockchip.md
- mkdocs.yml
As per subject, update rockchip multimedia status with latest bits and supported features.
> update rockchip multimedia status

- docs/User-Guide_FAQ.md
> Add heartbeat led info

- docs/Release_Changelog.md
> Recreate images for CM40 and M7

- docs/Release_Changelog.md
fix typo. We're not ahead of time...this time.
> fix version

- docs/User-Guide_FAQ.md
for some reason the upgrade instructions were duplicate
> duplicate entry

- docs/Community_IRC.md
- deprecate rss channel since broken for ages
- deprecate bot functions which were broken for ages too
- be more detailed about chat relays
- add 2nd choice for GUI IRC clients
- general wording/cosmetics
> deprecations/cosmetics for community/irc

- docs/User-Guide_FAQ.md
wording, updated userspaces, fixes
> adjustments

- docs/Developer-Guide_Build-Options.md
https://github.com/armbian/build/pull/6786
> Add new build option NETWORKING_STACK at build time

- docs/User-Guide_Getting-Started.md
After changes from https://github.com/armbian/build/pull/6823 are merged
> Update 1st login instructions

- docs/User-Guide_Networking.md
- Make more use of Markdown syntax
- Change the yaml config names to the ones used in the build framework to avoid issues with overwritings and confusions
- Add some links for reference
- Add some information
- Restructure some infos
> Improve networking guide

- docs/Developer-Guide_Build-Options.md
https://github.com/armbian/build/pull/6951
> add customized GHCR_MIRROR_ADDRESS support

- docs/User-Guide_Networking.md
> avoid docker conflict

- README.md
- mkdocs.yml
- requirements.txt
- tools/mkArmbianDocs.py
Also, update the installation command in the README.md file to use "--use-pep517" flag for pip install.
> Update requirements.txt to fix failing

- .github/workflows/merge-announce.yml
- .github/workflows/pr-announce.yml
just like `build` repo
secrets need to be set beforehand.
> Add discord webhooks

- docs/Developer-Guide_Build-Options.md
This PR is complimentary to https://github.com/armbian/build/pull/7086 and should be merged after the changes to the build are merged.
> Add `KERNEL_COMPILER` option description and fix some typos

- docs/Developer-Guide_Build-Options.md
https://github.com/armbian/build/pull/7216
> Add OPENSSHD_REGENERATE_HOST_KEYS

- docs/User-Guide_FAQ.md
Those links are generic and should update themselves due to changes on their end.
> be more precides about (un)supported userspaces

- docs/User-Guide_Getting-Started.md
Cosmetic changes in the download authenticity process.
<a href=https://armbian.github.io/documentation/491><kbd> <br> Open WWW preview <br> </kbd></a>
> Cosmetic adjustments: removing too many spaces in the code

- docs/Developer-Guide_Build-Preparation.md
- mkdocs.yml
<a href=https://armbian.github.io/documentation/494><kbd> <br> Open WWW preview <br> </kbd></a>
> Build framework documentation: rework getting started part

- docs/User-Guide_Armbian-Software.md
- mkdocs.yml
<a href=https://armbian.github.io/documentation/510><kbd> <br> Open WWW preview <br> </kbd></a>
This was changed / added:
https://armbian.github.io/documentation/510/User-Guide_Armbian-Software/
<a href=https://armbian.github.io/documentation/510><kbd> <br> Open WWW …
> Adding instructions for adding a software title to the armbian-config

- docs/User-Guide_Armbian-Software.md
https://github.com/armbian/configng/pull/203
<a href=https://armbian.github.io/documentation/514><kbd> <br> Open WWW preview <br> </kbd></a>
> Update software adding with latest functional changes

- docs/Developer-Guide_Build-Options.md
CRYPTSETUP arguments update for https://github.com/armbian/build/pull/7443.
> CRYPTSETUP args update

- docs/User-Guide_Armbian-Software.md
<a href=https://armbian.github.io/documentation/522><kbd> <br> Open WWW preview <br> </kbd></a>
> Add another PR example

- docs/Process_Contribute.md
<a href=https://armbian.github.io/documentation/520><kbd> <br> Open WWW preview <br> </kbd></a>
> Add additional source code targets

- docs/User-Guide_Armbian-Config.md
<a href=https://armbian.github.io/documentation/524><kbd> <br> Open WWW preview <br> </kbd></a>
> Sudo is not needed to start with

- docs/Developer-Guide_Build-Preparation.md
- docs/Developer-Guide_Overview.md
- mkdocs.yml
One small document improvements every day.
<a href=https://armbian.github.io/documentation/536><kbd> <br> Open WWW preview <br> </kbd></a>
> Improve framework welcome page, clean getting started

- docs/index.md
Its Monday, so another small improvements of documentation.
<a href=https://armbian.github.io/documentation/544><kbd> <br> Open WWW preview <br> </kbd></a>
> Improve part about advantages

- .github/workflows/pull-from-armbian-config.yml
- mkdocs.yml
<a href=https://armbian.github.io/documentation/549><kbd> <br> Open WWW preview <br> </kbd></a>
> Add Downloaders section

- docs/User-Guide_Networking.md
<a href=https://armbian.github.io/documentation/550><kbd> <br> Open WWW preview <br> </kbd></a>
> Improve wireless info

- docs/Release_Changelog.md
<a href=https://armbian.github.io/documentation/547><kbd> <br> Open WWW preview <br> </kbd></a>
> Add release info for 24.11.1

- docs/User-Guide_Advanced-Features.md
<a href=https://armbian.github.io/documentation/553><kbd> <br> Open WWW preview <br> </kbd></a>
> Update info regarding DKMS

- docs/User-Guide_Getting-Started.md
They feel odd
<a href=https://armbian.github.io/documentation/555><kbd> <br> Open WWW preview <br> </kbd></a>
> Remove a couple of question marks

- docs/Developer-Guide_Build-Switches.md
<a href=https://armbian.github.io/documentation/586><kbd> <br> Open WWW preview <br> </kbd></a>
> fix whitespace

- docs/index.md
<a href=https://armbian.github.io/documentation/589><kbd> <br> Open WWW preview <br> </kbd></a>
> Link to mirrors on this page

- .github/workflows/pull-from-armbian-config.yml
- mkdocs.yml
<a href=https://armbian.github.io/documentation/592><kbd> <br> Open WWW preview <br> </kbd></a>
> Add printing section

- docs/Developer-Guide_Build-Switches.md
- docs/User-Guide_FAQ.md
<a href=https://armbian.github.io/documentation/602><kbd> <br> Open WWW preview <br> </kbd></a>
> add `ARTIFACT_IGNORE_CACHE` to FAQ

- docs/Developer-Guide_Build-Switches.md
<a href=https://armbian.github.io/documentation/606><kbd> <br> Open WWW preview <br> </kbd></a>
> Add SKIP_ARMBIAN_REPO switch description

- docs/User-Guide_Armbian-Config.md
<a href=https://armbian.github.io/documentation/609><kbd> <br> Open WWW preview <br> </kbd></a>
> armbian-config: adding keys to the 3rd party install

- docs/Process_CI.md
<a href=https://armbian.github.io/documentation/620><kbd> <br> Open WWW preview <br> </kbd></a>
> Improve instructions for maintainers

- docs/Developer-Guide_Build-Switches.md
https://github.com/armbian/build/pull/7675
<a href=https://armbian.github.io/documentation/621><kbd> <br> Open WWW preview <br> </kbd></a>
> Add KERNEL_BTF

- docs/index.md
Fixed a few very minor typos on the home page.
> Fix typos on home page.

- docs/Release_Changelog.md
<a href=https://armbian.github.io/documentation/643><kbd> <br> Open WWW preview <br> </kbd></a>
> Upcoming release changes

- docs/Mirrors.md
<a href=https://armbian.github.io/documentation/648><kbd> <br> Open WWW preview <br> </kbd></a>
> Add a link to redirector sources

- docs/Developer-Guide_Build-Commands.md
- docs/Developer-Guide_Build-Preparation.md
<a href="https://armbian.github.io/documentation/668"><kbd><br> Open WWW preview <br></kbd></a>
> Cherry picking commits that were made to master branch

- docs/Developer-Guide_User-Configurations.md
made by @leggewie
<a href="https://armbian.github.io/documentation/669"><kbd><br> Open WWW preview <br></kbd></a>
> Several rewording

- README.md
<a href="https://armbian.github.io/documentation/672"><kbd><br> Open WWW preview <br></kbd></a>
> Improve text on README and fix broken badge

- docs/WifiPerformance.md
- mkdocs.yml
<a href="https://armbian.github.io/documentation/673"><kbd><br> Open WWW preview <br></kbd></a>
To section "contribute" for now:
```
- 'CONTRIBUTE' :
- 'Contribute' : 'Process_Contribute.md'
- 'Armbian config': 'Contribute/Armbian-config.md'
- 'Wifi performance tests': 'WifiPerformance.md'
```
> Add wireless performance testings page

- docs/WifiPerformance.md
Generate documentation.
<a href="https://armbian.github.io/documentation/675"><kbd><br> Open WWW preview <br></kbd></a>
> `Automatic` wireless performance tests

- mkdocs.yml
<a href="https://armbian.github.io/documentation/676"><kbd><br> Open WWW preview <br></kbd></a>
> Adjust edit button to point to main branch

- docs/Developer-Guide_Build-Switches.md
Related to https://github.com/armbian/build/pull/8053
> Add SECTOR_SIZE info

- docs/Mirrors.md
- docs/User-Guide_Board-Support-Rules.md
- docs/WifiPerformance.md
- overrides/main.html
<a href="https://armbian.github.io/documentation/671"><kbd><br> Open WWW preview <br></kbd></a>
<a href="https://armbian.github.io/documentation/671"><kbd><br> Open WWW preview <br></kbd></a>
> Adding commenting system and enable it at Mirrors page

- docs/Developer-Guide_Build-Preparation.md
to adapt BTF changes
<a href="https://armbian.github.io/documentation/688"><kbd><br> Open WWW preview <br></kbd></a>
> adjust requirements

- docs/Contribute/Armbian-config.md
- docs/User-Guide_Armbian-Software.md
<a href="https://armbian.github.io/documentation/694"><kbd><br> Open WWW preview <br></kbd></a>
> Fix contribution

- docs/css/armbian-extra.css
Font goes down on smaller pages:
<a href="https://armbian.github.io/documentation/697"><kbd><br> Open WWW preview <br></kbd></a>
> Make CSS responsive ready

- mkdocs.yml
<a href="https://armbian.github.io/documentation/700"><kbd><br> Open WWW preview <br></kbd></a>
> Add finance to the SW menu

- docs/User-Guide_Armbian-Software.md
<a href="https://armbian.github.io/documentation/710"><kbd><br> Open WWW preview <br></kbd></a>
> Improve software intro

- docs/WifiPerformance.md
<a href="https://armbian.github.io/documentation/724"><kbd><br> Open WWW preview <br></kbd></a>
> Add a link to GitHub action covering the testings

- docs/WifiPerformance.md
<a href="https://armbian.github.io/documentation/725"><kbd><br> Open WWW preview <br></kbd></a>
> Change link from Netbox website to our documentation

- docs/Developer-Guide_Build-Switches.md
Documentation for https://github.com/armbian/build/pull/8149
> Include documentation for DISABLE_KERNEL_PATCHES

- docs/Developer-Guide_Build-Preparation.md
<a href="https://armbian.github.io/documentation/741"><kbd><br> Open WWW preview <br></kbd></a>
> Update requirements - set default OS as Noble

- docs/Developer-Guide_Adding-Board-Family.md
Since we didn't manage to create some proper docs for this, at least provide more examples.
> add two more examples for adding new hw

- docs/WifiPerformance.md
<a href="https://armbian.github.io/documentation/764"><kbd><br> Open WWW preview <br></kbd></a>
> Add instructions for adding a device

- docs/User-Guide_Getting-Started.md
<a href="https://armbian.github.io/documentation/769"><kbd><br> Open WWW preview <br></kbd></a>
> A2 cards are good

- docs/Developer-Guide_Overview.md
<a href="https://armbian.github.io/documentation/786"><kbd><br> Open WWW preview <br></kbd></a>
> Move project structure from README.md

- mkdocs.yml
Let's see if docs still generate successfully in this PR.
Closing https://github.com/armbian/documentation/issues/802
<a href="https://armbian.github.io/documentation/804"><kbd><br> Open WWW preview <br></kbd></a>
> Remove duplicate configuration entry
