armbian/documentation

- docs/User-Guide_Getting-Started.md
when retrieving from keyserver.   It is important to use more than the old 32-bit shorthand, as they are readily faked.  See, for example, http://www.asheesh.org/note/debian/short-key-ids-are-bad-news.html and https://evil32.com/ and https://lkml.org/lkml/2016/8/15/445 (as if we needed more confirmation).
> Use full GPG key fingerprint

- docs/Developer-Guide_Build-Preparation.md
Placing each sentence on its own line allows for fewer "changed" lines when diff'ing between revisions. It is arguably also easier to read in source. I am not sure about markdown, but asciidoc uses this formatting style as standard.
> Fixed confusing verbiage; minor formatting

- docs/Developer-Guide_Build-Options.md
This commit relates to [my commit on build](https://github.com/armbian/build/pull/1182).
Further CRYPTROOT_SSH_PORT was wrong or outdated. Needs to be CRYPTROOT_SSH_UNLOCK_PORT
> Introduction of the CRYPTROOT_PARAMETERS variable

- tools/mkArmbianDocs.py
See issue #31 - the link to edit on github is broken
> Fix documentation URL (closes: #31)

- docs/Developer-Guide_Build-Preparation.md
I did a build of nanopineo2 4.19.13-sunxi64 and it failed with a 20G disk.
I did a build with a much bigger disk and in the end it consumed 23G
Hence my 25G min recommendation
> Increase min disk recommended 20 > 25G

- docs/Developer-Guide_Testing-Procedures.md
This is just one of (hopefully) many formalized testing procedures to help make life easier for everybody. This PR contributes toward resolution of issue #36.
I would prefer to have additional nesting within the headings (for example: Testing Procedures -> Hardware -> Micro SD card), but "Hardware" and "Micro SD card" appeared at the same level within the menu navigation bar on the left on my system. Therefore I collapsed them to be "Hardware: Micro SD card". Feel free to advise or edit.
> Add initial testing procedure: micro SD card compatibility

- docs/Developer-Guide_Using-Vagrant.md
Update documentation to refer to vagrant image "ubuntu/bionic64" instead of "ubunto/xenial64" since vagrant file was updated to xenial in https://github.com/armbian/build/commit/2c762ebd885c74eb45eb942c7d29b50d1e7a045b#diff-23b6f443c01ea2efcb4f36eedfea9089
> Change xenial to bionic in vagrant set up documentation

- docs/Hardware_Marvell.md
Hi,
as discussed here https://github.com/armbian/build/issues/1426 , I have updated the Marvell Armada docs page to reflect the new kernel versions. 
As they have been published now, please review this and merge if ok.
> Changed Marvell page to reflect new kernel and uboot versions and the regarding features

- docs/User-Guide_Recovery.md
A small adjustment, now that I am getting the hang of this.
I add main heading, and correct depth of others (that I simply copied before).  So now left menu sub-topics appear properly.
I did not change any names, so this should not affect any previously existing links.
> Adjust Recovery page heading depths

- docs/Developer-Guide_Using-Vagrant.md
- docs/Hardware_Allwinner-A20.md
- docs/Hardware_Freescale-imx6.md
- docs/Process_Release-Model.md
- docs/Release_Changelog.md
- docs/User-Guide_Advanced-Features.md
- docs/User-Guide_Armbian-Config.md
- docs/User-Guide_Fine-Tuning.md
- docs/User-Guide_Getting-Started.md
- docs/index.md
Many less links this time around.  However I want to note the various
reasons there were still some broken links:
In some cases, it was because httpS is not supported on some sites
where I might have expected it to be (Sourceforge, etc.) and were
(perhaps too optimistically) changed in last (mass) http to httpS
update.
In other cases, previously updated links needed to be updated to their
final redirect location, which could not be seen (easily) until the
changes went live.
In other cases, there were more than one link to same site with the
same problem, and I had only searched for one link on the page (and
thus missed the others).
And finally, in at least one case (F3) it appears the site already
went down in the meantime.
All of above cases should now be remedied.  However I do plan on …
> Fix more links after running wg.org link checking tool again

- tools/mkArmbianDocs.py
Inconsistent use of tabs and spaces in indentation prevents the script from running
> Fix TabError in mkArmbianDocs

- docs/Hardware_Freescale-imx6.md
- docs/User-Guide_Basic-Troubleshooting.md
The default Cubox-I / Hummingboard image have fdt_file set to imx6q-cubox-i.dbt and will not boot by default on a Hummingboard.
> Added device tree setup section to IMX6 documentation

- docs/Developer-Guide_Build-Options.md
* Mention defaults
* Clarify that `CRYPTROOT_PARAMETERS` should be space-separated
> Clarify cryptroot options

- docs/Developer-Guide_User-Configurations.md
Look at https://forum.armbian.com/topic/6-how-to-build-my-own-image-or-kernel/?do=findComment&comment=126636 
Old example is not actual, modern armbian has only BRANCH ( **legacy** | **current** | **dev** ) not **edge** because https://docs.armbian.com/Developer-Guide_Build-Options/ 
and "sunxi" looks not like a LINUXFAMILY but like a fake. (May be "sun7i"?) I think that armbian never can make this example message.
My example is real example from my system.
> Example of User provided kernel config

- docs/Developer-Guide_Build-Options.md
`edge` is used by a few boards instead of/in addition to `dev`, so listing it would be useful
`NO_APT_CACHER` is a build option printed as a warning when building within a container, so it should be listed in documentation
> list "edge" as a target BRANCH and list missing build option

- mkdocs.yml
Since we are not using it anyway.
This reduces local mkdocs re-generation from minutes to seconds.
It also prevents almost 10K lines of binary (document.pdf) from being
added to the docs repo with every PR.
See also: https://github.com/armbian/documentation/issues/171.
> mkdocs.yml: Comment out PDF automatic generation

- docs/Release_Board-Maintainers.md
antondeveloper is devdotnetorg on GitHub.
The reason the whole table was replaced, was because when I moved the
note 3 after his name, it changed the column width.  But there were no
other changes.
> docs/Release_Board-Maintainers.md: Update antondeveloper GitHub

- docs/Release_Board-Maintainers.md
Radxa Zero's support status is changed back to CSC and the board will no longer have a maintainer for Armbian's official support level. We will still provide the same level of support as before.
Also adding radxa-zero2. This was merged a while ago.
See armbian/build#3523
> docs/Release_Board-Maintainers.md: Remove RadxaYuntian

- docs/Release_Board-Maintainers.md
Fix schwar3kat should be maintainer for orangepizeroplus, not orangepizero.
> Fix - schwar3kat on wrong board

- docs/Developer-Guide_Building-with-Docker.md
For some reason, Markdown's enumerated lists are awful to deal with. This caused the (1. 2. 3.) list on docs.armbian.com to show up as (1. 1. 1.) This fix doesn't look right on GitHub but *should* render correctly on the site itself.
https://stackoverflow.com/a/63226685/12559797
> Fix bizarre enumerated list nonsense

- docs/Release_Board-Maintainers.md
Added myself as official maintainer for tinkerboard (rockchip 32 bit) and orangepi4-lts; also added myself in github -> forum name translation table.
> Add jock as maintainer for tinkerboard and orangepi4-lts

- docs/Community_Governance.md
Lane sadly left the SBC world, therefore a few positions now no longer have lead maintainer.
> Adjust governance

- docs/Developer-Guide_Build-Options.md
Reverts armbian/documentation#279
@EvilOlaf Please revert this merge, since based on the discussion on issue https://github.com/armbian/build/issues/4421 the appropriate script code pull request will not be merged. I will provide another pull request for a new `BUILD_ONLY` option on the build repo. When this has been accepted, I will create another pull request to the doc repo again.
I you mind, please have a look to https://github.com/armbian/build/issues/4421 for the details.
> Revert "Add UBOOT_ONLY option doc"

- mkdocs.yml
- tools/mkArmbianDocs.py
Add markdown extension pymdownx.emoji to mkdocs.yml.
s. https://github.com/MHARMBIAN/armbian_documentation/releases/download/6b4720e/armbian-document-6b4720e.pdf
Chapter **5.5 Build Options**
> Fix: Github emojis in markdown not rendered for the documentation

- .github/workflows/release.yaml
Current release workflow raises a couple of warnings:
This PR fixes the release workflow:
No warnings anymore:
> Fix warnings on documentation release workflow

- docs/User-Guide_Advanced-Features.md
The current steps resulted in GPG key warnings/error on apt update. With the updated steps from the docker docs it worked.
Note: This adds docker-compose, as docker docs suggest this by default. Fee free to drop is you think this is not needed.
> Update docker install steps to align with updated docker docs

- docs/Developer-Guide_Build-Preparation.md
These options are deprecated according to igor
> dev-guide-build-prep: remove deprecated options

- docs/Developer-Guide_Extensions-Hooks.md
…oper english this time)
Mixed before and after in documentation of the hook. (if it can be used the same way as `customize-image.sh` will be tested tomorrow, i think if the image is not mounted, you cant do system settings)
> testing the hook reveals it is called before `customize-image.sh` (proper sentence)

- docs/Release_Changelog.md
I was confused when I looked at the changelog and saw the out-of-order dates, but I looked into the change described and realized it was simply using a YYYY-DD-MM date format instead of the ISO 8601 YYYY-MM-DD format used by the rest of the changelog.
> Corrected latest change entry in Release_Changelog.md to use ISO 8601 date format.

- docs/Developer-Guide_Extensions.md
The documentation was incorrect with two underscores before the number.
Was confusing since the line after only had one.
> Should only be one underscore before 500

- docs/Community_IRC.md
Libera Matrix bridge were shut down
https://libera.chat/guides/matrix
We could bring it back if we create our own channel/s on some random Matrix server and "plumb" those into IRC (or simply use our matterbridge that exists already lol) but I have my doubts that it is worth the effort.
> remove matrix

- docs/Developer-Guide_Build-Options.md
Most of these options do not work or have potential to break the system such as the CRYPTROOT -> Advice against using it until it's updated
> Developer-Guide_Build-Options: Add warning about obsolescence

- docs/Developer-Guide_Build-Options.md
This apparently no longer supported - when using it I get:
```
[💥] error! [ LIB_TAG is set.This is not supported anymore. Please remove it, and manage the git branches manually.  ]
```
> Remove LIB_TAG

- docs/Developer-Guide_Build-Preparation.md
The removed parameter causes an eventual error during a build.  Removing the parameter allows the build to proceed.
* remove offending parameter, observe build completes
> fix: Remove deprecatated command line argument from example

- docs/Hardware_Rockchip.md
- mkdocs.yml
They are outdated. 
Page commented until somebody steps up and adds some new stuff like for rk3588 or whatever...
> disable rockchip hw notes

- docs/User-Guide_FAQ.md
For some reason the leading backslash of the first bracket is shown in the docs. Let's see what happens if I remove it but leave the other one for escape.
> Remove backslash

- docs/Developer-Guide_Build-Options.md
DEPRECATED message updated with warning sign and DEPRECATED text adde to the page title.
> Added CLI related merged PRs to the documentation

- docs/User-Guide_Networking.md
add release info
minor cosmetics
> minor fixes

- docs/User-Guide_Advanced-Features.md
Export kernel source directory a KSRC variable before building the driver and fix the building command to use $KSRC and M=$PWD to perform single kernel module build inside the out-of-tree kernel module directory.
Also add a reference link to official kbuild/modules documentations.
> Advanced_Features: fix building wifi driver guide

- README.md
Armbian 24.5.1 Bookworm with Linux 6.6.31-current-meson64
added  bash procedure used to build document in readme. 
Followed readme tutorial readme bash procedure did not work for me on fresh image of Armbian 24.5.1 Bookworm
what procedure did worked
```bash
{
sudo apt-get update
sudo apt-get install python3 python3-pip python3-venv python3.11-dev
}
```
followed by 
```bash
{
git clone https://github.com/armbian/documentation
cd documentation
python3 -m venv $HOME/.local/armbian-docs-env 
source $HOME/.local/armbian-docs-env/bin/activate
$HOME/.local/armbian-docs-env/bin/pip install -r requirements.txt
mkdocs build --clean && mkdocs serve
}
```
Lastly
This shows a the expected webpage on given `url:port`
```bash
python3 tools/mkArmbianDocs.py && mkdocs build 
mkdocs serve
```
resulted …
> updated readme.md with setup "Working on the content" instructions for armbian 24.5.1 

- docs/Process_Release-Model.md
For once they IMHO weren't as efficient as expected and weren't happening recently. So switch visibility for now.
> remove meetings

- README.md
Debian Bookworm does not come with `libcairo-2` or `pango1.0-tools` installed by default. `mkdocs-material` requires these packages.
> Added Debian package requirements to README.md

- .github/workflows/pdf-at-pr.yaml
This expand GitHub action to generate HTML preview on the fly, at PR, available within 2-3min at:
`https://armbian.github.io/documentation/PR_NUMBER`
This below is automatically created:
<hr>
<a href=https://armbian.github.io/documentation/490><kbd> <br> Open WWW preview <br> </kbd></a>
Documentation website preview will be available …
> Lets generate webpage preview at PR

- .github/workflows/pr-announce.yml
only send announcement when a PR is opened, nothing else.
untested
<a href=https://armbian.github.io/documentation/493><kbd> <br> Open WWW preview <br> </kbd></a>
> limit announcements for PRs

- .github/workflows/pdf-at-pr.yaml
<a href=https://armbian.github.io/documentation/500><kbd> <br> Open WWW preview <br> </kbd></a>
> Try to use dedicated secret

- .markdownlint.json
- docs/User-Guide_Autoconfig.md
- docs/User-Guide_Getting-Started.md
- docs/css/armbian-extra.css
- mkdocs.yml
(Almost) complete rewrite of User-Guide_Autoconfig to use a tabulated formatting
<a href=https://armbian.github.io/documentation/501><kbd> <br> Open WWW preview <br> </kbd></a>
> Format User-Guide_Autoconfig properly

- docs/Developer-Guide_Build-Commands.md
- docs/Developer-Guide_Build-Switches.md
Moved half of switches from deprecated section up - which are operational. I propose to merge this - with quick sanity check. Its more or less attempt of better organisation.
<a href=https://armbian.github.io/documentation/521><kbd> <br> Open WWW preview <br> </kbd></a>
> Improve build switches - part 1

- .github/workflows/pull-from-armbian-config.yml
- mkdocs.yml
Depends on: https://github.com/armbian/configng/pull/237
<a href=https://armbian.github.io/documentation/526><kbd> <br> Open WWW preview <br> </kbd></a>
> Add Monitoring section to the menu

- docs/Developer-Guide_Build-Switches.md
https://github.com/armbian/build/pull/7452
<a href=https://armbian.github.io/documentation/532><kbd> <br> Open WWW preview <br> </kbd></a>
> Remove WIREGUARD as its deprecated

- .gitignore
Adds `.DS_Store` to `gitignore` to ensure these files aren't synced
<a href=https://armbian.github.io/documentation/539><kbd> <br> Open WWW preview <br> </kbd></a>
> Update gitignore for mac

- .github/workflows/release.yaml
- mkdocs.yml
Update workflows to remove attempt to upload/download PDF - PDF is not currently built
Also removes extraneous whitespace in mkdocs YAML
<a href=https://armbian.github.io/documentation/541><kbd> <br> Open WWW preview <br> </kbd></a>
> x13-me: Update workflows, formatting

- docs/Developer-Guide_Build-Commands.md
Closing https://github.com/armbian/documentation/issues/431
<a href=https://armbian.github.io/documentation/543><kbd> <br> Open WWW preview <br> </kbd></a>
> Add rewrite-kernel-patches

- docs/User-Guide_Autoconfig.md
closes #537
<a href=https://armbian.github.io/documentation/542><kbd> <br> Open WWW preview <br> </kbd></a>
> Update Autoconfig with proposed changes

- docs/Process_Release-Model.md
<a href=https://armbian.github.io/documentation/559><kbd> <br> Open WWW preview <br> </kbd></a>
> Fix wrongly named release months

- docs/User-Guide_Armbian-Config.md
<a href=https://armbian.github.io/documentation/594><kbd> <br> Open WWW preview <br> </kbd></a>
> Add two links to armbian-config

- docs/User-Guide_Getting-Started.md
Etcher is known to be unreliable writing large images and has a spyware controversy attached to it. Therefore adjust recommendations.
<a href=https://armbian.github.io/documentation/598><kbd> <br> Open WWW preview <br> </kbd></a>
> remove etcher from recommendations

- docs/Developer-Guide_Build-Switches.md
update documentation to reflect new CCACHE default in 
https://github.com/armbian/build/pull/7730
<a href=https://armbian.github.io/documentation/603><kbd> <br> Open WWW preview <br> </kbd></a>
> USE_CCACHE: update documentation to show new default from PR #7730

- docs/Developer-Guide_Build-Preparation.md
Hello! In the documentation about the [Build Framework](https://docs.armbian.com/Developer-Guide_Overview/), specifically in the Getting Started section, [the paragraph dedicated to build options contains a broken link](https://docs.armbian.com/Developer-Guide_Build-Preparation/#cli): 404 not found.
I thought it would be appropriate to update it with the link dedicated to build options, as indicated in https://docs.armbian.com/Developer-Guide_Build-Switches/
I wanted to bring this oversight to your attention, thank you.
> docs(build): update link to build switches reference

- docs/User-Guide_Armbian-Config.md
Replace creation of `armbian-config.list` with `armbian-config.sources`. This holds the same information in a newer format, deb822. APT has supported this format since version 1.1, released in 2015.
This does not affect `armbian.list`.
See also:
- https://github.com/armbian/configng/pull/407
- https://github.com/armbian/build/pull/7782
> docs: Use deb822 APT source for armbian-config

- .github/workflows/pull-mirrors-from-db.yml
- Dynamically update the rsync table with current required space values (dl, apt, archive, oldarchive).
- Refresh the Current Mirrors section by querying the Netbox API.
- Preserve the static content (introduction, operational flow, etc.) of the document.
<a href=https://armbian.github.io/documentation/632><kbd> <br> Open WWW preview <br> </kbd></a>
> docs: update rsync and Current Mirrors sections

- docs/Developer-Guide_Build-Preparation.md
On the Armbian Build Framework > Getting Started page, add some notes about logging, to let users know where to find the logs and how to enable debug logs.
> Add notes about logging

- docs/Developer-Guide_User-Configurations.md
Text (mostly) from Ricardo from here: https://github.com/armbian/documentation/pull/344#discussion_r1242686073
<a href="https://armbian.github.io/documentation/678"><kbd><br> Open WWW preview <br></kbd></a>
> deprecate lib.config

- docs/Developer-Guide_Build-Switches.md
could introduce confusion if there is an extra _community_ patch set besides the regular one from Armbian.
<a href="https://armbian.github.io/documentation/729"><kbd><br> Open WWW preview <br></kbd></a>
> be more specific about disabling kernel patches

- .github/labeler.yml
- docs/Developer-Guide_User-Configurations.md
- docs/Process_CI.md
push a collection of small fixes to improve the documentation
> push a collection of small fixes to improve the documentation

- docs/WifiPerformance.md
Generate documentation.
<a href="https://armbian.github.io/documentation/738"><kbd><br> Open WWW preview <br></kbd></a>
> `Automatic` wireless performance tests

- docs/Developer-Guide_Build-Switches.md
Was missing
<a href="https://armbian.github.io/documentation/745"><kbd><br> Open WWW preview <br></kbd></a>
> add `SHARE_LOG` switch

- docs/Developer-Guide_Build-Switches.md
Documentation to match https://github.com/armbian/build/pull/8346 
<a href="https://armbian.github.io/documentation/773"><kbd><br> Open WWW preview <br></kbd></a>
> Add CPUTHREADS Build Switch

- docs/User-Guide_Getting-Started.md
This PR adds `rkdeveloptool` guides (linux / macos) as content tabs next to the classic installation via SD card.
> Getting Started: Add rkdeveloptool guide

- docs/User-Guide_FAQ.md
Why wasting time explaining over and over when this can be simply clarified in docs?
<a href="https://armbian.github.io/documentation/794"><kbd><br> Open WWW preview <br></kbd></a>
> Restore question about userspace upgrades

- docs/Developer-Guide_Build-Switches.md
- docs/Developer-Guide_User-Configurations.md
- mkdocs.yml
- requirements.txt
https://docs.armbian.com/User-Guide_Allwinner_overlays/ is referenced /boot/dtb/overlay/README.sun4i-a10-overlays and others.  It should redirect to https://docs.armbian.com/User-Guide_Armbian_overlays/ nowadays.
Including other small, cosmetic fixes in the PR.
> add redirect for https://docs.armbian.com/User-Guide_Allwinner_overlays/

- docs/User-Guide_Board-Support-Rules.md
the HTML anchor for the "Staging" heading isn't there, this PR fixes that
> fix staging anchor in "board suppport rules"

- docs/Developer-Guide_Build-Preparation.md
Hello everyone! I ran into a small compatibility issue when using the interactive UI. I’m using the Ghostty terminal emulator, and in this case the build process failed with a fatal error:
`'xterm-ghostty': unknown terminal type.`
I think this simple issue can affect users of modern terminal emulators such as Ghostty, Kitty, etc... 
These terminals often set a TERM environment variable (e.g., xterm-ghostty, xterm-kitty) that is not included in the default terminfo database available inside the build environment. As a result, text‑based user interface (TUI) tools like dialog cannot render.
I think it is enough to just add a small note in the documentation, as indicated in the commit.
> Overriding $TERM to a more compatible value like xterm-256color
